/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lat3;

/**
 *
 * @author john
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bil1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtonKurang = new javax.swing.JButton();
        ButtonKali = new javax.swing.JButton();
        ButtonBagi = new javax.swing.JButton();
        ButtonTambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Bil2 = new javax.swing.JTextField();
        Hasil = new javax.swing.JTextField();
        ButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kalkultor Sederhana");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 0, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bilangan 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 60, 70, 30);
        getContentPane().add(Bil1);
        Bil1.setBounds(190, 60, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("HASIL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 220, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Bilangan 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 100, 70, 30);

        ButtonKurang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonKurang.setText("-");
        ButtonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonKurang);
        ButtonKurang.setBounds(260, 170, 50, 50);

        ButtonKali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonKali.setText("X");
        ButtonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaliActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonKali);
        ButtonKali.setBounds(80, 170, 50, 50);

        ButtonBagi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonBagi.setText(":");
        ButtonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBagiActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBagi);
        ButtonBagi.setBounds(140, 170, 50, 50);

        ButtonTambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonTambah.setLabel("+");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonTambah);
        ButtonTambah.setBounds(200, 170, 50, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Operator");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 140, 70, 30);
        getContentPane().add(Bil2);
        Bil2.setBounds(190, 100, 90, 30);

        Hasil.setEditable(false);
        Hasil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        getContentPane().add(Hasil);
        Hasil.setBounds(120, 250, 140, 80);

        ButtonReset.setBackground(new java.awt.Color(255, 255, 255));
        ButtonReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonReset.setForeground(new java.awt.Color(255, 0, 51));
        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonReset);
        ButtonReset.setBounds(270, 260, 67, 23);

        setBounds(0, 0, 416, 383);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(String.valueOf(Bil1.getText()));
        int bil2 = Integer.parseInt(String.valueOf(Bil2.getText()));
        int hasil = bil1-bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonKurangActionPerformed

    private void ButtonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaliActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        int hasil = bil1*bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonKaliActionPerformed

    private void ButtonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBagiActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        int hasil = bil1 / bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonBagiActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        double bil1 = Double.parseDouble(String.valueOf(Bil1.getText()));
        double bil2 = Double.parseDouble(String.valueOf(Bil2.getText()));
        double hasil = bil1 + bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        Hasil.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bil1;
    private javax.swing.JTextField Bil2;
    private javax.swing.JButton ButtonBagi;
    private javax.swing.JButton ButtonKali;
    private javax.swing.JButton ButtonKurang;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JTextField Hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
